name: ci tests

on:
  push:
    branches: [main]

jobs:
  listFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: configuracion pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 11
      - name: Instalar dependencias
        run: pnpm install
      - name: Lint
        run: pnpm lint

  testFrontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: configuracion pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 11
      - name: Instalar dependencias
        run: pnpm install
      - name: Test
        run: pnpm test
